@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class combined {
   from_stop_i: numeric
   to_stop_i: numeric
   duration_avg: numeric
   route_i: numeric
}
class combxwalk {
   from_stop_i: numeric
   to_stop_i: numeric
   duration_avg: numeric
   route_i: text
}
class nodes {
   lat: numeric
   lon: numeric
   name: text
   stop_i: numeric
}
class route_rps {
   route_type: numeric
   route_name: text
   route_rps_i: numeric
}
class routes {
   route_type: numeric
   route_name: text
   route_i: numeric
}
class routexsuper {
   route_i: numeric
   route_rps_i: numeric
}
class short_walk {
   from_stop_i: numeric
   to_stop_i: numeric
   d_walk: numeric
   route_i: text
}
class stoproutename {
   name: text
   stop_i: numeric
   route_type: numeric
   route_name: text
}
class stopxroute {
   stop_i: numeric
   route_i: numeric
}
class super_route_comb {
   from_stop_i: numeric
   to_stop_i: numeric
   duration_avg: numeric
   route_rps_i: numeric
}
class temporal_day {
   from_stop_i: numeric
   to_stop_i: numeric
   dep_time_ut: numeric
   arr_time_ut: numeric
   route_type: numeric
   trip_i: numeric
   seq: numeric
   route_i: numeric
}
class walk {
   from_stop_i: numeric
   to_stop_i: numeric
   d_walk: numeric
   route_i: text
}

@enduml
